/**
 * 书单导入 · 批次 4
 * 由「安争鸣 / 小鸣说」YouTube 频道推荐书目整理而来。
 * 轻量条目：无长文简介，仅含书目事实字段 + 来源主题。
 * year / title_en 为 null 表示未能核实，不猜测。
 */
export const batch = [
  {
    slug: "starry-messenger",
    category: "technology",
    title_zh: "星际信使",
    title_en: "Starry Messenger: Cosmic Perspectives on Civilization",
    author: "neil-degrasse-tyson",
    author_zh: "尼尔·德格拉斯·泰森",
    author_en: "Neil deGrasse Tyson",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2022,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "宇宙学视角下的“大格局”",
    theme_en: "The big picture, seen from a cosmologist's perspective.",
    tags: ["cosmology","science","physics","society"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "zhege-yuzhou-he-wo-you-shenme-guanxi",
    category: "technology",
    title_zh: "这个宇宙和我有什么关系",
    title_en: null,
    author: "harald-lesch",
    author_zh: "哈拉尔德·莱施",
    author_en: "Harald Lesch",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 2019,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "物理学与冷漠宇宙中的存在意义",
    theme_en: "Physics, and finding meaning in an indifferent universe.",
    tags: ["cosmology","science","physics","philosophy"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "until-the-end-of-time",
    category: "technology",
    title_zh: "直到时间尽头",
    title_en: "Until the End of Time: Mind, Matter, and Our Search for Meaning in an Evolving Universe",
    author: "brian-greene",
    author_zh: "布莱恩·格林",
    author_en: "Brian Greene",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2020,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    also_in: ["xiaomingshuo"],
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "超弦理论、熵增与终极熵寂末日预言",
    theme_en: "String theory, entropy, and the end of everything.",
    tags: ["cosmology","physics","science","consciousness"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "suanfa-yu-yuyan",
    category: "technology",
    title_zh: "算法与预言",
    title_en: null,
    author: "alessandro-vespignani",
    author_zh: "历山德罗·韦斯皮尼亚尼",
    author_en: "Alessandro Vespignani",
    nationality_zh: "意大利",
    nationality_en: "Italy",
    year: 2019,
    original_language: "it",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "大数据预测、算法与社会演变",
    theme_en: "Big data, prediction, algorithms, and how society changes.",
    tags: ["technology","science","future-of-technology","risk"],
    topics: ["technology","science-and-nature"]
  },
  {
    slug: "visions-of-technological-transcendence",
    category: "technology",
    title_zh: "人类未来进化史",
    title_en: "Visions of Technological Transcendence: Human Enhancement and the Rhetoric of the Future",
    author: "james-a-herrick",
    author_zh: "詹姆斯·赫里克",
    author_en: "James A. Herrick",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2017,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "科技永生、传播学与人类演化",
    theme_en: "Technological immortality, rhetoric, and the future of human evolution.",
    tags: ["technology","future-of-technology","science","human-nature"],
    topics: ["technology","philosophy"]
  },
  {
    slug: "extraterrestrial",
    category: "technology",
    title_zh: "外星人",
    title_en: "Extraterrestrial: The First Sign of Intelligent Life Beyond Earth",
    author: "avi-loeb",
    author_zh: "阿维·洛布",
    author_en: "Avi Loeb",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2021,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "哈佛天文学家探讨外星文明与科学精神",
    theme_en: "A Harvard astronomer on alien civilizations and the scientific spirit.",
    tags: ["cosmology","science","physics"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "the-passions-and-the-interests",
    category: "economics",
    title_zh: "欲望与利益",
    title_en: "The Passions and the Interests: Political Arguments for Capitalism before Its Triumph",
    author: "albert-o-hirschman",
    author_zh: "艾伯特·赫希曼",
    author_en: "Albert O. Hirschman",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1977,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "资本主义欲望合法化的思想演变",
    theme_en: "How the pursuit of gain was made respectable before capitalism won.",
    tags: ["capitalism","economics","philosophy","history"],
    topics: ["philosophy","history"]
  },
  {
    slug: "our-symphony-with-animals",
    category: "technology",
    title_zh: "伴生：我们与动物的故事",
    title_en: "Our Symphony with Animals: On Health, Empathy, and Our Shared Destinies",
    author: "aysha-akhtar",
    author_zh: "阿伊莎·阿赫塔",
    author_en: "Aysha Akhtar",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2019,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "动物伦理与文明社会秩序基础",
    theme_en: "Animal ethics and the foundations of a civilized social order.",
    tags: ["science","neuroscience","ethics","human-nature"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "the-selfish-gene",
    category: "technology",
    title_zh: "自私的基因",
    title_en: "The Selfish Gene",
    author: "richard-dawkins",
    author_zh: "理查德·道金斯",
    author_en: "Richard Dawkins",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1976,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "基因演化论与反人文主义倾向",
    theme_en: "Gene-centred evolution and its anti-humanist implications.",
    tags: ["evolution","genetics","science","human-nature"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "the-naked-ape",
    category: "technology",
    title_zh: "裸猿",
    title_en: "The Naked Ape: A Zoologist's Study of the Human Animal",
    author: "desmond-morris",
    author_zh: "德斯蒙德·莫里斯",
    author_en: "Desmond Morris",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1967,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "把人类当作一种动物来考察",
    theme_en: "The human being examined as just another animal.",
    tags: ["evolution","human-nature","science","psychology"],
    topics: ["science-and-nature","cognitive-science"]
  },
  {
    slug: "the-meaning-of-human-existence",
    category: "technology",
    title_zh: "人类存在的意义",
    title_en: "The Meaning of Human Existence",
    author: "edward-o-wilson",
    author_zh: "爱德华·威尔逊",
    author_en: "Edward O. Wilson",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2014,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "社会生物学视角下的演化与人文主义",
    theme_en: "Evolution and humanism seen through sociobiology.",
    tags: ["evolution","science","philosophy","human-nature"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "you-bet-your-life",
    category: "technology",
    title_zh: "赌命",
    title_en: "You Bet Your Life: From Blood Transfusions to Mass Vaccination, the Long and Risky History of Medical Innovation",
    author: "paul-a-offit",
    author_zh: "保罗·奥菲特",
    author_en: "Paul A. Offit",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2021,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "医疗风险、疫苗研发与科学理性",
    theme_en: "Medical risk, vaccine development, and the case for scientific reasoning.",
    tags: ["science","risk","uncertainty","decision-making"],
    topics: ["risk","science-and-nature"]
  },
  {
    slug: "letter-to-a-child-never-born",
    category: "literature",
    title_zh: "给一个未能出生的孩子的信",
    title_en: "Letter to a Child Never Born",
    author: "oriana-fallaci",
    author_zh: "奥里亚娜·法拉奇",
    author_en: "Oriana Fallaci",
    nationality_zh: "意大利",
    nationality_en: "Italy",
    year: 1975,
    original_language: "it",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "自然科学、宇宙与生命科普",
    list_category_en: "Natural Science, Cosmos & Life",
    theme_zh: "生育本质、存在主义与生命辩驳",
    theme_en: "The nature of motherhood, existentialism, and an argument for life.",
    tags: ["fiction","gender","family","philosophy"],
    topics: ["gender-and-family","literature"]
  },
  {
    slug: "shiyu-jixian",
    category: "society",
    title_zh: "始于极限",
    title_en: null,
    author: "chizuko-ueno",
    author_zh: "上野千鹤子",
    author_en: "Chizuko Ueno",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2021,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "12个女性议题书信对谈，向下自由非自由",
    theme_en: "Twelve letters on women's issues, and why downward freedom is no freedom.",
    tags: ["feminism","gender","japan","society"],
    topics: ["gender-and-family","modern-society"]
  },
  {
    slug: "zai-shuxi-de-jiazhong-xiang-shijie-daobie",
    category: "society",
    title_zh: "在熟悉的家中向世界道别",
    title_en: null,
    author: "chizuko-ueno",
    author_zh: "上野千鹤子",
    author_en: "Chizuko Ueno",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2021,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "直面老龄化、独居老人的晚年尊严",
    theme_en: "Facing old age, and the dignity of living alone at the end of life.",
    tags: ["japan","family","society","modern-world"],
    topics: ["modern-society","gender-and-family"]
  },
  {
    slug: "yannu",
    category: "society",
    title_zh: "厌女",
    title_en: null,
    author: "chizuko-ueno",
    author_zh: "上野千鹤子",
    author_en: "Chizuko Ueno",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2010,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "社会性厌女与女人的自我厌女",
    theme_en: "Social misogyny and the misogyny women turn on themselves.",
    tags: ["feminism","gender","japan","society"],
    topics: ["gender-and-family","modern-society"]
  },
  {
    slug: "wuyuan-shehui",
    category: "society",
    title_zh: "无缘社会",
    title_en: null,
    author: "nhk-special-reporting-team",
    author_zh: "NHK特别追踪报道组",
    author_en: "NHK Special Reporting Team",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2010,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "日本“孤独死”现象与传统婚姻解体",
    theme_en: "Japan's solitary deaths and the unraveling of traditional marriage.",
    tags: ["japan","society","modern-world","family"],
    topics: ["modern-society","gender-and-family"]
  },
  {
    slug: "ta-yannan-ta-shi-wo-nvyou",
    category: "society",
    title_zh: "她厌男，她是我女友",
    title_en: null,
    author: "min-jihyoung",
    author_zh: "闵智炯",
    author_en: "Min Jihyoung",
    nationality_zh: "韩国",
    nationality_en: "South Korea",
    year: 2019,
    original_language: "ko",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "韩国普通男性与女性主义者的观念分歧",
    theme_en: "An ordinary Korean man and a feminist: the gap between their worlds.",
    tags: ["fiction","novel","feminism","gender","korea"],
    topics: ["gender-and-family","literature"]
  },
  {
    slug: "not-just-for-the-boys",
    category: "society",
    title_zh: "一直在场",
    title_en: "Not Just for the Boys: Why We Need More Women in Science",
    author: "athene-donald",
    author_zh: "雅典娜·唐纳德",
    author_en: "Athene Donald",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2023,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "科学界的隐性性别歧视与女性人才流失",
    theme_en: "Hidden sexism in science and the women it drives away.",
    tags: ["feminism","gender","science","society"],
    topics: ["gender-and-family","science-and-nature"]
  },
  {
    slug: "the-gender-knot",
    category: "society",
    title_zh: "性别打结",
    title_en: "The Gender Knot: Unraveling Our Patriarchal Legacy",
    author: "allan-g-johnson",
    author_zh: "艾伦·约翰逊",
    author_en: "Allan G. Johnson",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1997,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "经典女性主义社会学入门，剖析父权制",
    theme_en: "A classic feminist introduction to how patriarchy actually works.",
    tags: ["gender","feminism","society","power"],
    topics: ["gender-and-family","power-and-politics"]
  },
  {
    slug: "li-yinhe-shuo-aiqing",
    category: "society",
    title_zh: "李银河说爱情",
    title_en: null,
    author: "li-yinhe",
    author_zh: "李银河",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2019,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "单身生活、性与爱情社会学",
    theme_en: "The sociology of single life, sex, and love.",
    tags: ["gender","family","society","china"],
    topics: ["gender-and-family","modern-society"]
  },
  {
    slug: "heading-home",
    category: "society",
    title_zh: "回归家庭",
    title_en: "Heading Home: Motherhood, Work, and the Failed Promise of Equality",
    author: "shani-orgad",
    author_zh: "沙尼·奥加德",
    author_en: "Shani Orgad",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2019,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "结构性暴力与女性职业退碍",
    theme_en: "Structural violence and why women step back from their careers.",
    tags: ["feminism","gender","family","inequality"],
    topics: ["gender-and-family","class-and-inequality"]
  },
  {
    slug: "a-room-of-ones-own",
    category: "society",
    title_zh: "一间自己的屋子",
    title_en: "A Room of One's Own",
    author: "virginia-woolf",
    author_zh: "弗吉尼亚·伍尔夫",
    author_en: "Virginia Woolf",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1929,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "女性创作的物质基础与独立空间",
    theme_en: "The money and private space a woman needs in order to write.",
    tags: ["feminism","gender","society","classics"],
    topics: ["gender-and-family","literature"]
  },
  {
    slug: "shaonian-fasheng",
    category: "society",
    title_zh: "少年发声",
    title_en: null,
    author: "chen-yu",
    author_zh: "陈瑜",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2021,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "性别研究、女性主义与婚姻家庭",
    list_category_en: "Gender Studies, Feminism & Family",
    theme_zh: "16位中国少年的访谈，中式家教与窒息感",
    theme_en: "Sixteen Chinese teenagers on family upbringing and the feeling of suffocation.",
    tags: ["family","china","society","psychology"],
    topics: ["gender-and-family","modern-society"]
  },
  {
    slug: "the-politics-of-social-solidarity",
    category: "economics",
    title_zh: "福利大博弈",
    title_en: "The Politics of Social Solidarity: Class Bases of the European Welfare State, 1875–1975",
    author: "peter-baldwin",
    author_zh: "彼得·鲍德温",
    author_en: "Peter Baldwin",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1990,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "欧洲福利制度起源与社会团结",
    theme_en: "The origins of Europe's welfare states and the politics of solidarity.",
    tags: ["welfare","inequality","institutions","history","economics"],
    topics: ["class-and-inequality","history"]
  },
  {
    slug: "coffeeland",
    category: "economics",
    title_zh: "咖啡帝国",
    title_en: "Coffeeland: One Man's Dark Empire and the Making of Our Favorite Drug",
    author: "augustine-sedgewick",
    author_zh: "奥古斯丁·赛奇威克",
    author_en: "Augustine Sedgewick",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2020,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "全球化掠夺与资本主义扩张史",
    theme_en: "Global plunder and the expansion of capitalism, told through coffee.",
    tags: ["capitalism","globalization","business","history"],
    topics: ["class-and-inequality","history"]
  },
  {
    slug: "relationships-5-0",
    category: "society",
    title_zh: "关系5.0",
    title_en: "Relationships 5.0: How AI, VR, and Robots Will Reshape Our Emotional Lives",
    author: "elyakim-kislev",
    author_zh: "伊里亚金·基斯列夫",
    author_en: "Elyakim Kislev",
    nationality_zh: "以色列",
    nationality_en: "Israel",
    year: 2022,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "机器人、AI与人机共生情感革命",
    theme_en: "Robots, AI, and the coming revolution in human-machine intimacy.",
    tags: ["ai","technology","family","society","future-of-technology"],
    topics: ["ai","gender-and-family"]
  },
  {
    slug: "shehui-weishenme-dui-nianqingren-lengku-wuqing",
    category: "economics",
    title_zh: "社会为什么对年轻人冷酷无情",
    title_en: null,
    author: "masahiro-yamada",
    author_zh: "山田昌弘",
    author_en: "Masahiro Yamada",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2013,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "日本与东亚年轻人的向下流动与冷酷困境",
    theme_en: "Downward mobility and the harsh predicament of young people in East Asia.",
    tags: ["japan","inequality","society","family"],
    topics: ["class-and-inequality","modern-society"]
  },
  {
    slug: "complexity-the-evolution-of-earths-biodiversity",
    category: "technology",
    title_zh: "生命大趋势",
    title_en: "Complexity: The Evolution of Earth's Biodiversity and the Future of Humanity",
    author: "unknown-complexity",
    author_zh: null,
    author_en: null,
    nationality_zh: null,
    nationality_en: null,
    year: 2016,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "生物多样性与人类社会宏观趋势",
    theme_en: "Biodiversity and the large-scale trends of human society.",
    tags: ["evolution","science","complexity","systems-thinking"],
    topics: ["science-and-nature","complexity"]
  },
  {
    slug: "we-have-never-been-middle-class",
    category: "economics",
    title_zh: "我们从未中产过",
    title_en: "We Have Never Been Middle Class: How Social Mobility Misleads Us",
    author: "hadas-weiss",
    author_zh: "豪道斯·魏斯",
    author_en: "Hadas Weiss",
    nationality_zh: "以色列",
    nationality_en: "Israel",
    year: 2019,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "中产阶级脆弱性与返贫机制",
    theme_en: "The fragility of the middle class and how people slide back down.",
    tags: ["inequality","capitalism","society","economics"],
    topics: ["class-and-inequality","modern-society"]
  },
  {
    slug: "the-fuzzy-and-the-techie",
    category: "economics",
    title_zh: "文艺呆与科技宅",
    title_en: "The Fuzzy and the Techie: Why the Liberal Arts Will Rule the Digital World",
    author: "scott-hartley",
    author_zh: "斯科特·哈特里",
    author_en: "Scott Hartley",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2017,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "硅谷文科无用论反思，人文思维价值",
    theme_en: "Against Silicon Valley's disdain for the humanities.",
    tags: ["technology","innovation","business","society"],
    topics: ["technology","innovation"]
  },
  {
    slug: "sanshi-buli",
    category: "economics",
    title_zh: "三十不立",
    title_en: null,
    author: "nhk-special-reporting-team",
    author_zh: "NHK特别追踪报道组",
    author_en: "NHK Special Reporting Team",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2010,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "泡沫破裂后的年轻代际贫困",
    theme_en: "Generational poverty among the young after the bubble burst.",
    tags: ["japan","society","inequality","modern-world"],
    topics: ["class-and-inequality","modern-society"]
  },
  {
    slug: "00-niandai-de-xiangxiangli",
    category: "society",
    title_zh: "00年代的想象力",
    title_en: null,
    author: "tsunehiro-uno",
    author_zh: "宇野常宽",
    author_en: "Tsunehiro Uno",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2008,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "经济、商业与社会阶层",
    list_category_en: "Economics, Business & Social Class",
    theme_zh: "流行文化视角的社会心理与代际幻灭",
    theme_en: "Pop culture, social psychology, and the disillusion of a generation.",
    tags: ["japan","society","cultural-history","modern-world"],
    topics: ["modern-society","art-and-culture"]
  }
];
