/**
 * 书单导入 · 批次 3
 * 由「安争鸣 / 小鸣说」YouTube 频道推荐书目整理而来。
 * 轻量条目：无长文简介，仅含书目事实字段 + 来源主题。
 * year / title_en 为 null 表示未能核实，不猜测。
 */
export const batch = [
  {
    slug: "democratic-ideals-and-reality",
    category: "history",
    title_zh: "陆权论",
    title_en: "Democratic Ideals and Reality",
    author: "halford-mackinder",
    author_zh: "哈尔福德·麦金德",
    author_en: "Halford Mackinder",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1919,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "地缘政治学，海权与陆权思维对抗",
    theme_en: "Geopolitics and the contest between sea power and land power.",
    tags: ["politics","power","strategy","history"],
    topics: ["power-and-politics","history","civilization"]
  },
  {
    slug: "gong-su-xi-fang-wen-hua-jing-shen-de-yan-bian",
    category: "history",
    title_zh: "共塑：西方文化精神的演变",
    title_en: null,
    author: "zhao-lin",
    author_zh: "赵林",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2023,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "基督教信仰与人文/理性主义共塑西方",
    theme_en: "How Christian faith and humanist reason together shaped the West.",
    tags: ["cultural-history","religion","philosophy","civilization"],
    topics: ["civilization","history","religion-and-meaning"]
  },
  {
    slug: "gu-luo-ma-di-guo-de-hui-huang",
    category: "history",
    title_zh: "古罗马帝国的辉煌",
    title_en: null,
    author: "zhao-lin",
    author_zh: "赵林",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2023,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "古罗马兴衰与独裁帝国的扩张",
    theme_en: "Rome's rise and fall and the expansion of an autocratic empire.",
    tags: ["empires","ancient-civilizations","institutions","cultural-history"],
    topics: ["history","civilization","power-and-politics"]
  },
  {
    slug: "russia-under-the-old-regime",
    category: "history",
    title_zh: "旧制度下的俄国",
    title_en: "Russia Under the Old Regime",
    author: "richard-pipes",
    author_zh: "理查德·派普斯",
    author_en: "Richard Pipes",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1974,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "沙俄体制史与极权制度演变",
    theme_en: "The history of tsarist rule and the making of totalitarian institutions.",
    tags: ["russia","institutions","politics","authoritarianism"],
    topics: ["authoritarianism","power-and-politics","history"]
  },
  {
    slug: "aftermath-life-in-the-fallout-of-the-third-reich",
    category: "history",
    title_zh: "狼性时代",
    title_en: "Aftermath: Life in the Fallout of the Third Reich",
    author: "harald-jahner",
    author_zh: "哈拉尔德·耶纳",
    author_en: "Harald Jähner",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 2019,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "战后德国（1945-1955）社会心理重构",
    theme_en: "Rebuilding everyday psychology in Germany after the war, 1945 to 1955.",
    tags: ["germany","world-wars","cultural-history","modern-world"],
    topics: ["history","modern-society","civilization"]
  },
  {
    slug: "wen-ming-da-qu-shi",
    category: "history",
    title_zh: "文明大趋势",
    title_en: null,
    author: "su-san",
    author_zh: "苏三",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2014,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "地缘传播逻辑与中华文明命运",
    theme_en: "The logic of geographic diffusion and the fate of Chinese civilization.",
    tags: ["china","civilization","cultural-history","history"],
    topics: ["civilization","history","china-and-the-world"]
  },
  {
    slug: "zuo-jia-cheng-bao",
    category: "history",
    title_zh: "作家城堡",
    title_en: null,
    author: "uwe-neumahr",
    author_zh: "乌韦·诺伊玛尔",
    author_en: "Uwe Neumahr",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 2023,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "纽伦堡审判期间各方记者的历史视角",
    theme_en: "The Nuremberg trials as seen by journalists from every side.",
    tags: ["germany","world-wars","cultural-history","politics"],
    topics: ["history","art-and-culture","power-and-politics"]
  },
  {
    slug: "rise-and-kill-first",
    category: "history",
    title_zh: "先发制人",
    title_en: "Rise and Kill First: The Secret History of Israel's Targeted Assassinations",
    author: "ronen-bergman",
    author_zh: "罗南·伯格曼",
    author_en: "Ronen Bergman",
    nationality_zh: "以色列",
    nationality_en: "Israel",
    year: 2018,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "摩萨德暗杀行动史与中东局势",
    theme_en: "The history of Mossad assassinations and the Middle East they shaped.",
    tags: ["politics","power","institutions","modern-world"],
    topics: ["power-and-politics","history","authoritarianism"]
  },
  {
    slug: "february-1933-the-winter-of-literature",
    category: "history",
    title_zh: "文学之冬：1933年...",
    title_en: "February 1933: The Winter of Literature",
    author: "uwe-wittstock",
    author_zh: "乌维·维特斯托克",
    author_en: "Uwe Wittstock",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 2021,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "纳粹上台后艺术家的流亡与消亡",
    theme_en: "Artists exiled and silenced after the Nazis came to power.",
    tags: ["germany","authoritarianism","cultural-history","politics"],
    topics: ["authoritarianism","art-and-culture","history"]
  },
  {
    slug: "why-dont-we-learn-from-history",
    category: "history",
    title_zh: "战争的底层逻辑",
    title_en: "Why Don't We Learn from History?",
    author: "b-h-liddell-hart",
    author_zh: "B. H. 李德·哈特",
    author_en: "B. H. Liddell Hart",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1944,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "战略大师遗作，掌权者的愚蠢与历史教训",
    theme_en: "A strategist's last work on the folly of rulers and history's lessons.",
    tags: ["history","strategy","politics","power"],
    topics: ["history","power-and-politics","strategy"]
  },
  {
    slug: "zhu-wang-de-ou-zhou",
    category: "history",
    title_zh: "诸王的欧洲",
    title_en: null,
    author: "leonhard-horowski",
    author_zh: "莱昂哈德·霍洛夫斯基",
    author_en: "Leonhard Horowski",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 2017,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "17-18世纪欧洲宫廷政治与旧体制坍塌",
    theme_en: "Court politics and the collapse of the old order in 17th and 18th century Europe.",
    tags: ["empires","politics","cultural-history","modern-world"],
    topics: ["power-and-politics","history","civilization"]
  },
  {
    slug: "zi-you-de-wen-hua",
    category: "history",
    title_zh: "自由的文化：古希腊与...",
    title_en: null,
    author: "christian-meier",
    author_zh: "克里斯蒂安·迈耶",
    author_en: "Christian Meier",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 2009,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "希腊城邦自由条件与欧洲起源",
    theme_en: "The conditions of freedom in the Greek polis and the origins of Europe.",
    tags: ["ancient-civilizations","democracy","cultural-history","classics"],
    topics: ["civilization","democracy-and-liberty","history"]
  },
  {
    slug: "huo-zhe-hui-lai-de-nan-ren",
    category: "history",
    title_zh: "活着回来的男人",
    title_en: null,
    author: "eiji-oguma",
    author_zh: "小熊英二",
    author_en: "Eiji Oguma",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2015,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "二战普通日本兵生命史与“人矿”炼成",
    theme_en: "An ordinary Japanese soldier's life story, and how people become raw material.",
    tags: ["japan","world-wars","memoir","modern-world"],
    topics: ["history","modern-society","literature"]
  },
  {
    slug: "culture-matters",
    category: "history",
    title_zh: "文化的重要作用",
    title_en: "Culture Matters: How Values Shape Human Progress",
    author: "samuel-huntington",
    author_zh: "塞缪尔·亨廷顿",
    author_en: "Samuel Huntington",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2000,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "价值观如何影响国家与文明进步",
    theme_en: "How values shape the progress of nations and civilizations.",
    tags: ["cultural-history","society","economics","civilization"],
    topics: ["civilization","modern-society","history"]
  },
  {
    slug: "the-coming-of-the-third-reich",
    category: "history",
    title_zh: "第三帝国的到来",
    title_en: "The Coming of the Third Reich",
    author: "richard-j-evans",
    author_zh: "理查德·J. 埃文斯",
    author_en: "Richard J. Evans",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2003,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "威玛共和国瓦解与纳粹掌权史",
    theme_en: "The collapse of the Weimar Republic and the Nazi seizure of power.",
    tags: ["germany","politics","institutions","authoritarianism"],
    topics: ["authoritarianism","power-and-politics","history"]
  },
  {
    slug: "heart-of-darkness",
    category: "literature",
    title_zh: "黑暗的心",
    title_en: "Heart of Darkness",
    author: "joseph-conrad",
    author_zh: "约瑟夫·康拉德",
    author_en: "Joseph Conrad",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1899,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "殖民主义掠夺与宏大叙事幻灭",
    theme_en: "Colonial plunder and the shattering of a grand narrative.",
    tags: ["fiction","novel","modernism","classics"],
    topics: ["literature","civilization","modern-society"]
  },
  {
    slug: "you-suo-bu-wei-de-fan-pan-zhe",
    category: "history",
    title_zh: "有所不为的反叛者",
    title_en: null,
    author: "luo-xin",
    author_zh: "罗新",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2019,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "历史、文明与国际政治",
    list_category_en: "History, Civilization & International Politics",
    theme_zh: "历史学散文，历史观批判与质疑",
    theme_en: "Essays on history that question how we know the past.",
    tags: ["history","china","cultural-history","classics"],
    topics: ["history","civilization","power-and-politics"]
  },
  {
    slug: "religion-without-god",
    category: "philosophy",
    title_zh: "没有上帝的宗教",
    title_en: "Religion Without God",
    author: "ronald-dworkin",
    author_zh: "罗纳德·德沃金",
    author_en: "Ronald Dworkin",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2013,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "无神论者的宗教感与客观价值",
    theme_en: "A religious sensibility without God, and the case for objective value.",
    tags: ["religion","atheism","ethics","philosophy"],
    topics: ["religion-and-meaning","philosophy"]
  },
  {
    slug: "the-god-delusion",
    category: "philosophy",
    title_zh: "上帝的错觉",
    title_en: "The God Delusion",
    author: "richard-dawkins",
    author_zh: "理查德·道金斯",
    author_en: "Richard Dawkins",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2006,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "激进无神论，对传统宗教的全面解构",
    theme_en: "Militant atheism and a full dismantling of traditional religion.",
    tags: ["atheism","religion","evolution","science"],
    topics: ["religion-and-meaning","science-and-nature","philosophy"]
  },
  {
    slug: "mind-and-cosmos",
    category: "philosophy",
    title_zh: "心灵和宇宙",
    title_en: "Mind and Cosmos: Why the Materialist Neo-Darwinian Conception of Nature Is Almost Certainly False",
    author: "thomas-nagel",
    author_zh: "托马斯·内格尔",
    author_en: "Thomas Nagel",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2012,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "质疑唯物论与还原论，倡导心灵研究",
    theme_en: "Doubts about materialism and reductionism, and a case for studying mind.",
    tags: ["philosophy","consciousness","science","evolution"],
    topics: ["philosophy","science-and-nature","cognitive-science"]
  },
  {
    slug: "the-wisdom-of-insecurity",
    category: "philosophy",
    title_zh: "心安：致焦虑的时代",
    title_en: "The Wisdom of Insecurity: A Message for an Age of Anxiety",
    author: "alan-watts",
    author_zh: "阿伦·瓦兹",
    author_en: "Alan Watts",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1951,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "东方禅宗与西方形而上学解焦",
    theme_en: "Zen and Western metaphysics as ways out of anxiety.",
    tags: ["philosophy","religion","psychology","classics"],
    topics: ["religion-and-meaning","philosophy","existentialism"]
  },
  {
    slug: "the-stillborn-god",
    category: "philosophy",
    title_zh: "夭折的上帝",
    title_en: "The Stillborn God: Religion, Politics, and the Modern West",
    author: "mark-lilla",
    author_zh: "马克·里拉",
    author_en: "Mark Lilla",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2007,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "政治神学、启蒙运动与现代西方",
    theme_en: "Political theology, the Enlightenment, and the modern West.",
    tags: ["religion","politics","philosophy","institutions"],
    topics: ["religion-and-meaning","power-and-politics","philosophy"]
  },
  {
    slug: "just-babies",
    category: "philosophy",
    title_zh: "善恶之源",
    title_en: "Just Babies: The Origins of Good and Evil",
    author: "paul-bloom",
    author_zh: "保罗·布鲁姆",
    author_en: "Paul Bloom",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2013,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "婴儿道德研究与普世价值形成",
    theme_en: "What infants reveal about morality and the making of universal values.",
    tags: ["ethics","psychology","human-nature","cognitive-science"],
    topics: ["philosophy","cognitive-science","science-and-nature"]
  },
  {
    slug: "memorabilia",
    category: "philosophy",
    title_zh: "回忆苏格拉底",
    title_en: "Memorabilia",
    author: "xenophon",
    author_zh: "色诺芬",
    author_en: "Xenophon",
    nationality_zh: "古希腊",
    nationality_en: "Ancient Greece",
    year: -371,
    original_language: "grc",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "追忆苏格拉底的品德与对话",
    theme_en: "Recollections of Socrates' character and conversations.",
    tags: ["classics","philosophy","ethics","ancient-civilizations"],
    topics: ["philosophy","history"]
  },
  {
    slug: "the-hemlock-cup",
    category: "philosophy",
    title_zh: "毒堇之杯",
    title_en: "The Hemlock Cup: Socrates, Athens and the Search for the Good Life",
    author: "bettany-hughes",
    author_zh: "贝尼塔·休斯",
    author_en: "Bettany Hughes",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2010,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "还原苏格拉底的时代与大众盲从",
    theme_en: "Reconstructing Socrates' Athens and the crowd's readiness to condemn.",
    tags: ["classics","ancient-civilizations","philosophy","democracy"],
    topics: ["philosophy","civilization","democracy-and-liberty"]
  },
  {
    slug: "yi-ge-bei-guan-zhu-yi-zhe-de-ji-ji-si-kao",
    category: "philosophy",
    title_zh: "一个悲观主义者的积极思考",
    title_en: null,
    author: "arthur-schopenhauer",
    author_zh: "亚瑟·叔本华",
    author_en: "Arthur Schopenhauer",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: null,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "悲观主义哲学在现实生活中的实用智慧",
    theme_en: "Pessimist philosophy as practical wisdom for everyday life.",
    tags: ["philosophy","existentialism","ethics","classics"],
    topics: ["philosophy","existentialism","religion-and-meaning"]
  },
  {
    slug: "on-the-laws",
    category: "philosophy",
    title_zh: "论法律",
    title_en: "On the Laws",
    author: "cicero",
    author_zh: "西塞罗",
    author_en: "Cicero",
    nationality_zh: "古罗马",
    nationality_en: "Ancient Rome",
    year: -52,
    original_language: "la",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "恶法非法、自然法与正义界定",
    theme_en: "Unjust law, natural law, and what justice actually is.",
    tags: ["classics","philosophy","institutions","ethics"],
    topics: ["philosophy","power-and-politics","democracy-and-liberty"]
  },
  {
    slug: "the-story-of-mankind",
    category: "philosophy",
    title_zh: "人类的故事",
    title_en: "The Story of Mankind",
    author: "hendrik-willem-van-loon",
    author_zh: "亨德里克·威廉·房龙",
    author_en: "Hendrik Willem van Loon",
    nationality_zh: "荷兰裔美国",
    nationality_en: "Dutch-American",
    year: 1921,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "人文主义精神与人类共同体视角",
    theme_en: "A humanist telling of civilization as one shared human story.",
    tags: ["history","civilization","classics","cultural-history"],
    topics: ["history","civilization","modern-society"]
  },
  {
    slug: "yue-du-shi-an-jing-de-zi-wo-jue-xing",
    category: "philosophy",
    title_zh: "阅读是安静的自我觉醒",
    title_en: null,
    author: "hermann-hesse",
    author_zh: "赫尔曼·黑塞",
    author_en: "Hermann Hesse",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: null,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "哲学、思想与信仰",
    list_category_en: "Philosophy, Thought & Belief",
    theme_zh: "主动阅读、集中专注与精神滋养",
    theme_en: "Active reading, sustained attention, and the nourishment of the mind.",
    tags: ["philosophy","classics","existentialism","human-nature"],
    topics: ["literature","philosophy","existentialism"]
  }
];
