/**
 * 书单导入 · 批次 5
 * 由「安争鸣 / 小鸣说」YouTube 频道推荐书目整理而来。
 * 轻量条目：无长文简介，仅含书目事实字段 + 来源主题。
 * year / title_en 为 null 表示未能核实，不猜测。
 */
export const batch = [
  /* 注：小鸣说书单中的《历史的终结及最后之人》（福山，1992）
   * 与策展经典 the-end-of-history 为同一本书，已由策展条目承载完整内容，
   * 此处不再重复收录，避免同一本书生成两个页面。 */
  {
    slug: "soulstealers",
    category: "society",
    title_zh: "叫魂：1768年中国妖术大恐慌",
    title_en: "Soulstealers",
    author: "philip-kuhn",
    author_zh: "孔飞力",
    author_en: "Philip A. Kuhn",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 1990,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "政治学、社会学与历史反思",
    list_category_en: "Politics, Sociology & Historical Reflection",
    theme_zh: "透过乾隆年间割发案，看专制君权与官僚体制的运行逻辑",
    theme_en: "A Qianlong-era sorcery panic reveals how autocratic power and bureaucracy work.",
    tags: ["china","history","power","society","classics"],
    topics: ["power-and-politics","history","china-and-the-world"]
  },
  {
    slug: "the-book-of-lord-shang",
    category: "society",
    title_zh: "商君书",
    title_en: "The Book of Lord Shang",
    author: "shang-yang",
    author_zh: "商鞅",
    author_en: "Shang Yang",
    co_author_note: "《商君书》非一人一时之作，学界多认为由商鞅及其后学编成",
    nationality_zh: "中国",
    nationality_en: "Chinese",
    year: null,
    original_language: "zh",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "政治学、社会学与历史反思",
    list_category_en: "Politics, Sociology & Historical Reflection",
    theme_zh: "法家「弱民、贫民、愚民」的驭民之术与专制制度基因",
    theme_en: "The Legalist art of weakening, impoverishing, and dulling the people to rule them.",
    tags: ["china","politics","authoritarianism","philosophy","classics"],
    topics: ["power-and-politics","authoritarianism","philosophy"]
  },
  {
    slug: "nhk-special-reporting-team-documentary-series",
    category: "society",
    title_zh: "NHK特别取材组纪实丛书",
    title_en: null,
    author: "nhk-special-reporting-team",
    author_zh: "日本NHK特别取材组",
    author_en: "NHK Special Reporting Team",
    co_author_note: "丛书由 NHK 特别取材组集体采写，含《老后破产》《女性贫困》《青年失业》等，非个人著作",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: null,
    original_language: "ja",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "政治学、社会学与历史反思",
    list_category_en: "Politics, Sociology & Historical Reflection",
    theme_zh: "记录日本老龄化、孤独死与无缘社会的残酷现场",
    theme_en: "Documenting ageing, solitary deaths, and Japan's disconnected society up close.",
    tags: ["japan","society","welfare","inequality","modern-world"],
    topics: ["modern-society","class-and-inequality"]
  },
  {
    slug: "the-path-of-least-resistance",
    category: "society",
    title_zh: "最小阻力路径相关社会学著作",
    title_en: null,
    author: "allan-johnson",
    author_zh: "艾伦·约翰逊",
    author_en: "Allan G. Johnson",
    co_author_note: "书单未指明具体书名，为艾伦·约翰逊社会学著作中「阻力最小路径」概念的相关论述",
    nationality_zh: "美国",
    nationality_en: "American",
    year: null,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "政治学、社会学与历史反思",
    list_category_en: "Politics, Sociology & Historical Reflection",
    theme_zh: "体制如何铺就「阻力最小的路径」，让人无意识顺从",
    theme_en: "How institutions pave a path of least resistance that makes conformity automatic.",
    tags: ["society","power","human-nature","systems-thinking"],
    topics: ["power-and-politics","modern-society"]
  },
  {
    slug: "the-world-as-will-and-representation",
    category: "philosophy",
    title_zh: "作为意志和表象的世界",
    title_en: "The World as Will and Representation",
    author: "arthur-schopenhauer",
    author_zh: "亚瑟·叔本华",
    author_en: "Arthur Schopenhauer",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 1818,
    original_language: "de",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "哲学思潮与思想史",
    list_category_en: "Philosophical Movements & Intellectual History",
    theme_zh: "现象世界只是表象，物自体是盲目的生存意志",
    theme_en: "The visible world is mere representation; reality itself is blind will.",
    tags: ["philosophy","existentialism","classics"],
    topics: ["philosophy","existentialism"]
  },
  {
    slug: "critique-of-pure-reason",
    category: "philosophy",
    title_zh: "纯粹理性批判",
    title_en: "Critique of Pure Reason",
    author: "immanuel-kant",
    author_zh: "伊曼努尔·康德",
    author_en: "Immanuel Kant",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 1781,
    original_language: "de",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "哲学思潮与思想史",
    list_category_en: "Philosophical Movements & Intellectual History",
    theme_zh: "先验认知结构划定理性边界，区分现象界与物自体",
    theme_en: "How our cognitive structure bounds reason, dividing appearance from things in themselves.",
    tags: ["philosophy","ethics","cognitive-science","classics"],
    topics: ["philosophy","cognitive-science"]
  },
  {
    slug: "symposium",
    category: "philosophy",
    title_zh: "会饮篇",
    title_en: "Symposium",
    author: "plato",
    author_zh: "柏拉图",
    author_en: "Plato",
    nationality_zh: "古希腊",
    nationality_en: "Ancient Greek",
    year: null,
    original_language: "el",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "哲学思潮与思想史",
    list_category_en: "Philosophical Movements & Intellectual History",
    theme_zh: "借宴会祝词探讨爱神厄洛斯的本质与灵魂的上升",
    theme_en: "Banquet speeches on the nature of Eros and the ascent of the soul.",
    tags: ["philosophy","classics","ethics"],
    topics: ["philosophy","religion-and-meaning"]
  },
  {
    slug: "a-treatise-of-human-nature",
    category: "philosophy",
    title_zh: "人性论",
    title_en: "A Treatise of Human Nature",
    author: "david-hume",
    author_zh: "大卫·休谟",
    author_en: "David Hume",
    nationality_zh: "苏格兰",
    nationality_en: "Scottish",
    year: 1739,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "哲学思潮与思想史",
    list_category_en: "Philosophical Movements & Intellectual History",
    theme_zh: "挑战因果必然性，认为因果只是人类的心理习惯",
    theme_en: "Challenging causal necessity: causation as nothing but a habit of the mind.",
    tags: ["philosophy","ethics","psychology","classics"],
    topics: ["philosophy","cognitive-science"]
  },
  {
    slug: "iliad-and-odyssey",
    category: "literature",
    title_zh: "荷马史诗（伊利亚特奥德赛）",
    title_en: "Iliad & Odyssey",
    author: "homer",
    author_zh: "荷马",
    author_en: "Homer",
    nationality_zh: "古希腊",
    nationality_en: "Ancient Greek",
    year: null,
    original_language: "el",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "史诗文学、古典著作与奇书",
    list_category_en: "Epic Literature, Classical Works & Curious Books",
    theme_zh: "阿基里斯之怒与奥德修斯的长航，西方文学之源",
    theme_en: "The wrath of Achilles and Odysseus's long voyage, the source of Western literature.",
    tags: ["epic","poetry","classics","ancient-civilizations"],
    topics: ["literature","history"]
  },
  {
    slug: "aeneid",
    category: "literature",
    title_zh: "埃涅阿斯纪",
    title_en: "Aeneid",
    author: "virgil",
    author_zh: "维吉尔",
    author_en: "Virgil",
    nationality_zh: "古罗马",
    nationality_en: "Roman",
    year: null,
    original_language: "la",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "史诗文学、古典著作与奇书",
    list_category_en: "Epic Literature, Classical Works & Curious Books",
    theme_zh: "埃涅阿斯背负神谕与建国使命的奉献史诗",
    theme_en: "An epic of duty, as Aeneas carries a divine command to found a nation.",
    tags: ["epic","poetry","classics","ancient-civilizations"],
    topics: ["literature","history"]
  },
  {
    slug: "ars-amatoria",
    category: "literature",
    title_zh: "爱经（爱的艺术）",
    title_en: "Ars Amatoria",
    author: "ovid",
    author_zh: "奥维德",
    author_en: "Ovid",
    nationality_zh: "古罗马",
    nationality_en: "Roman",
    year: null,
    original_language: "la",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "史诗文学、古典著作与奇书",
    list_category_en: "Epic Literature, Classical Works & Curious Books",
    theme_zh: "古罗马两性相处与恋爱的诗篇，曾被列为禁书",
    theme_en: "A Roman poem on courtship and love, once banned for its candour.",
    tags: ["poetry","classics","cultural-history","gender"],
    topics: ["literature","art-and-culture"]
  },
  {
    slug: "satyricon",
    category: "literature",
    title_zh: "萨蒂利孔",
    title_en: "Satyricon",
    author: "petronius",
    author_zh: "佩特罗尼乌斯",
    author_en: "Petronius",
    nationality_zh: "古罗马",
    nationality_en: "Roman",
    year: null,
    original_language: "la",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "史诗文学、古典著作与奇书",
    list_category_en: "Epic Literature, Classical Works & Curious Books",
    theme_zh: "尼禄时期的流浪汉小说，讽刺社会放纵与奢靡",
    theme_en: "A picaresque satire of excess and luxury in Nero's Rome.",
    tags: ["fiction","novel","classics","cultural-history"],
    topics: ["literature","art-and-culture"]
  },
  {
    slug: "the-decameron",
    category: "literature",
    title_zh: "十日谈",
    title_en: "The Decameron",
    author: "giovanni-boccaccio",
    author_zh: "乔万尼·薄伽丘",
    author_en: "Giovanni Boccaccio",
    nationality_zh: "意大利",
    nationality_en: "Italian",
    year: 1353,
    original_language: "it",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "史诗文学、古典著作与奇书",
    list_category_en: "Epic Literature, Classical Works & Curious Books",
    theme_zh: "黑死病中的故事集，批判教会腐败、歌颂人文",
    theme_en: "Plague-time tales that mock a corrupt Church and celebrate human wit.",
    tags: ["short-stories","fiction","classics","religion"],
    topics: ["literature","religion-and-meaning"]
  },
  {
    slug: "childe-harolds-pilgrimage",
    category: "literature",
    title_zh: "恰尔德·哈罗尔德游记",
    title_en: "Childe Harold's Pilgrimage",
    author: "lord-byron",
    author_zh: "拜伦",
    author_en: "Lord Byron",
    nationality_zh: "英国",
    nationality_en: "British",
    year: 1812,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "史诗文学、古典著作与奇书",
    list_category_en: "Epic Literature, Classical Works & Curious Books",
    theme_zh: "拜伦式英雄的漫游，抒发对自由与反抗的渴望",
    theme_en: "A Byronic wanderer's travels and his longing for liberty and revolt.",
    tags: ["poetry","classics","cultural-history"],
    topics: ["literature","art-and-culture"]
  },
  {
    slug: "the-psychopath-inside",
    category: "psychology",
    title_zh: "天生变态狂",
    title_en: "The Psychopath Inside",
    author: "james-fallon",
    author_zh: "詹姆斯·法隆",
    author_en: "James Fallon",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 2013,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "脑科学、心理学、基因与前沿科学",
    list_category_en: "Neuroscience, Psychology, Genetics & Frontier Science",
    theme_zh: "神经学家发现自己拥有反社会大脑的自剖",
    theme_en: "A neuroscientist's self-dissection after finding he has a psychopath's brain.",
    tags: ["neuroscience","psychology","genetics","human-nature"],
    topics: ["science-and-nature","cognitive-science"]
  },
  {
    slug: "rewire-your-anxious-brain",
    category: "psychology",
    title_zh: "重塑与情绪修复脑科学",
    title_en: null,
    author: "catherine-m-pittman",
    author_zh: "凯特琳·M·特曼",
    author_en: "Catherine M. Pittman",
    co_author_note: "作者栏标注「等」，原书另有合著者",
    nationality_zh: "美国",
    nationality_en: "American",
    year: null,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "脑科学、心理学、基因与前沿科学",
    list_category_en: "Neuroscience, Psychology, Genetics & Frontier Science",
    theme_zh: "杏仁核与皮层的焦虑机制，及基于脑科学的应对",
    theme_en: "The amygdala, the cortex, and brain-based ways to rewire anxiety.",
    tags: ["neuroscience","psychology","cognitive-science","decision-making"],
    topics: ["cognitive-science","science-and-nature"]
  },
  {
    slug: "testosterone",
    category: "psychology",
    title_zh: "睾酮",
    title_en: "Testosterone",
    author: "carole-hooven",
    author_zh: "卡罗尔·胡文",
    author_en: "Carole Hooven",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 2021,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "脑科学、心理学、基因与前沿科学",
    list_category_en: "Neuroscience, Psychology, Genetics & Frontier Science",
    theme_zh: "睾酮如何影响男性体能、攻击性与竞争行为",
    theme_en: "What testosterone does to male strength, aggression, and competitive drive.",
    tags: ["neuroscience","psychology","evolution","human-nature"],
    topics: ["science-and-nature","cognitive-science"]
  },
  {
    slug: "dirty-genes",
    category: "psychology",
    title_zh: "脏基因",
    title_en: "Dirty Genes",
    author: "ben-lynch",
    author_zh: "本·林奇",
    author_en: "Ben Lynch",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 2018,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "脑科学、心理学、基因与前沿科学",
    list_category_en: "Neuroscience, Psychology, Genetics & Frontier Science",
    theme_zh: "表观遗传学：用饮食与生活方式优化基因表达",
    theme_en: "Epigenetics: tuning gene expression through diet and lifestyle.",
    tags: ["genetics","science","evolution","human-nature"],
    topics: ["science-and-nature","technology"]
  },
  {
    slug: "the-fermi-paradox-seventy-five-solutions",
    category: "technology",
    title_zh: "费米悖论的75种解释",
    title_en: null,
    author: "stephen-webb",
    author_zh: "史蒂芬·韦伯",
    author_en: "Stephen Webb",
    nationality_zh: "英国",
    nationality_en: "British",
    year: null,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "脑科学、心理学、基因与前沿科学",
    list_category_en: "Neuroscience, Psychology, Genetics & Frontier Science",
    theme_zh: "系统梳理动物园、大过滤器、稀有地球等假说",
    theme_en: "A systematic survey of the Zoo, Great Filter, Rare Earth and other hypotheses.",
    tags: ["science","physics","cosmology","future-of-technology"],
    topics: ["science-and-nature","technology"]
  },
  {
    slug: "biocentrism",
    category: "technology",
    title_zh: "生物中心主义三部曲",
    title_en: "Biocentrism",
    author: "robert-lanza",
    author_zh: "罗伯特·兰扎",
    author_en: "Robert Lanza",
    co_author_note: "合著者：鲍勃·伯曼（Bob Berman）",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 2009,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "脑科学、心理学、基因与前沿科学",
    list_category_en: "Neuroscience, Psychology, Genetics & Frontier Science",
    theme_zh: "宇宙并非独立存在，而由生命与意识所定义",
    theme_en: "The universe does not stand alone: life and consciousness define it.",
    tags: ["consciousness","physics","cosmology","philosophy"],
    topics: ["science-and-nature","philosophy"]
  },
  {
    slug: "the-easterlin-paradox",
    category: "economics",
    title_zh: "幸福经济学相关著作",
    title_en: null,
    author: "richard-easterlin",
    author_zh: "理查德·伊斯特林",
    author_en: "Richard Easterlin",
    co_author_note: "书单未指明具体书名，指向伊斯特林关于「伊斯特林悖论」的幸福经济学论述",
    nationality_zh: "美国",
    nationality_en: "American",
    year: null,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "经济学、幸福学与人生指南",
    list_category_en: "Economics, Happiness & Life Guides",
    theme_zh: "伊斯特林悖论：收入增加未必持续提升幸福感",
    theme_en: "The Easterlin paradox: more income does not reliably buy more happiness.",
    tags: ["economics","behavioral-economics","psychology","human-nature"],
    topics: ["behavioral-economics","decision-making"]
  },
  {
    slug: "the-cafe-on-the-edge-of-the-world",
    category: "economics",
    title_zh: "世界尽头的咖啡馆系列",
    title_en: "The Cafe on the Edge of the World",
    author: "john-strelecky",
    author_zh: "约翰·史崔勒基",
    author_en: "John Strelecky",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 2003,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "经济学、幸福学与人生指南",
    list_category_en: "Economics, Happiness & Life Guides",
    theme_zh: "追问存在目的，摆脱社会标准答案与多重身份",
    theme_en: "Asking what life is for, and shedding society's ready-made answers.",
    tags: ["philosophy","existentialism","fiction","psychology"],
    topics: ["existentialism","religion-and-meaning"]
  },
  {
    slug: "a-travel-guide-to-heaven",
    category: "economics",
    title_zh: "天堂之旅",
    title_en: "A Travel Guide to Heaven",
    author: "anthony-destefano",
    author_zh: "安东尼·德斯蒂法诺",
    author_en: "Anthony DeStefano",
    nationality_zh: "美国",
    nationality_en: "American",
    year: 2003,
    original_language: "en",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "经济学、幸福学与人生指南",
    list_category_en: "Economics, Happiness & Life Guides",
    theme_zh: "梳理基督教文献中天堂的环境、身体与生活",
    theme_en: "What Christian texts say about heaven's landscape, bodies, and daily life.",
    tags: ["religion","cultural-history","classics"],
    topics: ["religion-and-meaning","philosophy"]
  },
  {
    slug: "the-philosophy-of-art",
    category: "society",
    title_zh: "艺术哲学",
    title_en: "The Philosophy of Art",
    author: "hippolyte-taine",
    author_zh: "伊波利特·丹纳",
    author_en: "Hippolyte Taine",
    nationality_zh: "法国",
    nationality_en: "French",
    year: 1865,
    original_language: "fr",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "艺术史与文化赏析",
    list_category_en: "Art History & Cultural Appreciation",
    theme_zh: "艺术即模仿，种族、环境、时代决定艺术风格",
    theme_en: "Art as imitation, and how race, milieu, and era determine style.",
    tags: ["art","cultural-history","philosophy","classics"],
    topics: ["art-and-culture","philosophy"]
  },
  {
    slug: "tiancai-de-shenghui",
    category: "society",
    title_zh: "天才的盛会：文艺复兴艺术300年",
    title_en: null,
    author: "jiang-zhulang",
    author_zh: "江逐浪",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "Chinese",
    year: 2025,
    original_language: "zh",
    tier: "list",
    source: "xiaomingshuo",
    list_category_zh: "艺术史与文化赏析",
    list_category_en: "Art History & Cultural Appreciation",
    theme_zh: "以圣母百花大教堂为线索梳理文艺复兴三百年",
    theme_en: "Three centuries of the Renaissance, traced through Florence's cathedral dome.",
    tags: ["art","cultural-history","history"],
    topics: ["art-and-culture","history"]
  }
];
