/**
 * 书单导入 · 批次 2
 * 由「安争鸣 / 小鸣说」YouTube 频道推荐书目整理而来。
 * 轻量条目：无长文简介，仅含书目事实字段 + 来源主题。
 * year / title_en 为 null 表示未能核实，不猜测。
 */
export const batch = [
  {
    slug: "animal-farm",
    category: "literature",
    title_zh: "动物农场",
    title_en: "Animal Farm",
    author: "george-orwell",
    author_zh: "乔治·奥威尔",
    author_en: "George Orwell",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1945,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "《动物农场》政治寓言与中央计划经济批判",
    theme_en: "A political fable, and a critique of central planning.",
    tags: ["fiction","dystopia","politics"],
    topics: ["literature","power-and-politics"]
  },
  {
    slug: "runaway",
    category: "literature",
    title_zh: "逃离",
    title_en: "Runaway",
    author: "alice-munro",
    author_zh: "艾丽丝·门罗",
    author_en: "Alice Munro",
    nationality_zh: "加拿大",
    nationality_en: "Canada",
    year: 2004,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "诺贝尔文学奖作品，女性逃离与困境思考",
    theme_en: "Nobel-winning stories about women who run away and the predicaments they face.",
    tags: ["fiction","short-stories","nobel-laureate","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "chance",
    category: "literature",
    title_zh: "机缘",
    title_en: "Chance",
    author: "alice-munro",
    author_zh: "艾丽丝·门罗",
    author_en: "Alice Munro",
    nationality_zh: "加拿大",
    nationality_en: "Canada",
    year: 2004,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "女博士与女性特质、理性的悖论",
    theme_en: "A woman scholar, femininity, and the paradox of reason.",
    tags: ["fiction","short-stories","nobel-laureate"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "beneath-the-wheel",
    category: "literature",
    title_zh: "在轮下",
    title_en: "Beneath the Wheel",
    author: "hermann-hesse",
    author_zh: "赫尔曼·黑塞",
    author_en: "Hermann Hesse",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 1906,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "压抑的教育制度与被驯化的灵魂",
    theme_en: "A repressive school system and the souls it tames.",
    tags: ["fiction","novel","nobel-laureate","classics"],
    topics: ["literature","modern-society"]
  },
  {
    slug: "demian",
    category: "literature",
    title_zh: "德米安（彷徨少年时）",
    title_en: "Demian",
    author: "hermann-hesse",
    author_zh: "赫尔曼·黑塞",
    author_en: "Hermann Hesse",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 1919,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "精神觉醒、自我觉察与独立思考",
    theme_en: "Spiritual awakening, self-awareness, and learning to think for oneself.",
    tags: ["fiction","novel","nobel-laureate","existentialism","classics"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "the-kiss-to-the-leper",
    category: "literature",
    title_zh: "给麻风病人的吻",
    title_en: "The Kiss to the Leper",
    author: "francois-mauriac",
    author_zh: "弗朗索瓦·莫里亚克",
    author_en: "François Mauriac",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1922,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "传统婚姻的痛苦与人性刻画",
    theme_en: "The misery of a traditional marriage, and a portrait of human nature.",
    tags: ["fiction","novel","nobel-laureate","religion","classics"],
    topics: ["literature","religion-and-meaning","gender-and-family"]
  },
  {
    slug: "the-desert-of-love",
    category: "literature",
    title_zh: "爱的荒漠",
    title_en: "The Desert of Love",
    author: "francois-mauriac",
    author_zh: "弗朗索瓦·莫里亚克",
    author_en: "François Mauriac",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1925,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "诺奖作品，家庭缺陷与爱的匮乏",
    theme_en: "A Nobel laureate's study of a broken family and the scarcity of love.",
    tags: ["fiction","novel","nobel-laureate","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "genitrix",
    category: "literature",
    title_zh: "母亲大人",
    title_en: "Genitrix",
    author: "francois-mauriac",
    author_zh: "弗朗索瓦·莫里亚克",
    author_en: "François Mauriac",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1923,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "父权制受害者与畸形母子关系",
    theme_en: "Victims of patriarchy and a twisted bond between mother and son.",
    tags: ["fiction","novel","nobel-laureate","family","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "therese-desqueyroux",
    category: "literature",
    title_zh: "苔蕾丝·德斯盖鲁",
    title_en: "Thérèse Desqueyroux",
    author: "francois-mauriac",
    author_zh: "弗朗索瓦·莫里亚克",
    author_en: "François Mauriac",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1927,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "法国文学经典，谋杀丈夫的女性心理",
    theme_en: "A French classic about a wife who poisons her husband, and the mind behind it.",
    tags: ["fiction","novel","nobel-laureate","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "never-let-me-go",
    category: "literature",
    title_zh: "莫失莫忘（别让我走）",
    title_en: "Never Let Me Go",
    author: "kazuo-ishiguro",
    author_zh: "石黑一雄",
    author_en: "Kazuo Ishiguro",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2005,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "克隆人与“人矿”社会和解的反乌托邦探讨",
    theme_en: "A dystopia about clones making peace with a society that harvests them.",
    tags: ["fiction","novel","dystopia","nobel-laureate","classics"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "the-wall",
    category: "literature",
    title_zh: "隐墙",
    title_en: "The Wall",
    author: "marlen-haushofer",
    author_zh: "玛尔伦·豪斯霍费尔",
    author_en: "Marlen Haushofer",
    nationality_zh: "奥地利",
    nationality_en: "Austria",
    year: 1963,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "墙内生活、孤独与冷战心理隐喻",
    theme_en: "Solitude behind an invisible wall, and the psychology of the Cold War.",
    tags: ["fiction","novel","dystopia","modernism"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "the-moon-and-sixpence",
    category: "literature",
    title_zh: "月亮与六便士",
    title_en: "The Moon and Sixpence",
    author: "w-somerset-maugham",
    author_zh: "威廉·萨默塞特·毛姆",
    author_en: "W. Somerset Maugham",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1919,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "理想与现实的冲突，天才与普通人的边界",
    theme_en: "Ideals against reality, and the line between genius and ordinary life.",
    tags: ["fiction","novel","art","classics"],
    topics: ["literature","art-and-culture"]
  },
  {
    slug: "accidental-death-of-an-anarchist",
    category: "literature",
    title_zh: "一个无政府主义者的意外死亡",
    title_en: "Accidental Death of an Anarchist",
    author: "dario-fo",
    author_zh: "达里奥·福",
    author_en: "Dario Fo",
    nationality_zh: "意大利",
    nationality_en: "Italy",
    year: 1970,
    original_language: "it",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "政治讽刺剧，国家机器与权力批判",
    theme_en: "A political farce aimed at the machinery of the state and its power.",
    tags: ["drama","fiction","politics","nobel-laureate"],
    topics: ["literature","power-and-politics"]
  },
  {
    slug: "giovannis-room",
    category: "literature",
    title_zh: "乔瓦尼的房间",
    title_en: "Giovanni's Room",
    author: "james-baldwin",
    author_zh: "詹姆斯·鲍德温",
    author_en: "James Baldwin",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1956,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "同性群体边缘生存与性压抑",
    theme_en: "Marginal life and sexual repression among gay men in Paris.",
    tags: ["fiction","novel","gender","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "greek-lessons",
    category: "literature",
    title_zh: "失语者",
    title_en: "Greek Lessons",
    author: "han-kang",
    author_zh: "韩江",
    author_en: "Han Kang",
    nationality_zh: "韩国",
    nationality_en: "South Korea",
    year: 2011,
    original_language: "ko",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "诺奖得主作品，语言丧失与内心探索",
    theme_en: "A Nobel laureate's novel of lost language and inward searching.",
    tags: ["fiction","novel","nobel-laureate","modernism"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "a-happy-death",
    category: "literature",
    title_zh: "快乐的死",
    title_en: "A Happy Death",
    author: "albert-camus",
    author_zh: "阿尔贝·加缪",
    author_en: "Albert Camus",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1971,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "加缪处女作，生存虚无与反抗",
    theme_en: "Camus's first novel on the void of existence and the impulse to rebel.",
    tags: ["fiction","novel","existentialism","philosophy"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "ward-no-6",
    category: "literature",
    title_zh: "第六病室",
    title_en: "Ward No. 6",
    author: "anton-chekhov",
    author_zh: "安东·契诃夫",
    author_en: "Anton Chekhov",
    nationality_zh: "俄罗斯",
    nationality_en: "Russia",
    year: 1892,
    original_language: "ru",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "专制压迫下知识分子的反抗与妥协",
    theme_en: "Intellectuals under despotism, caught between resistance and resignation.",
    tags: ["fiction","short-stories","russia","classics"],
    topics: ["literature","power-and-politics"]
  },
  {
    slug: "the-tartar-steppe",
    category: "literature",
    title_zh: "鞑靼人沙漠",
    title_en: "The Tartar Steppe",
    author: "dino-buzzati",
    author_zh: "迪诺·布扎蒂",
    author_en: "Dino Buzzati",
    nationality_zh: "意大利",
    nationality_en: "Italy",
    year: 1940,
    original_language: "it",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "政治抑郁、听床与虚无日常的消耗",
    theme_en: "Political melancholy, rumour, and the slow drain of an empty daily life.",
    tags: ["fiction","novel","existentialism","modernism"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "fear",
    category: "literature",
    title_zh: "恐惧",
    title_en: "Fear",
    author: "stefan-zweig",
    author_zh: "斯蒂芬·茨威格",
    author_en: "Stefan Zweig",
    nationality_zh: "奥地利",
    nationality_en: "Austria",
    year: 1920,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "心理悬疑经典，婚外情与PUA操控",
    theme_en: "A psychological thriller of adultery and manipulative control.",
    tags: ["fiction","novel","psychology","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "simple-passion",
    category: "literature",
    title_zh: "简单的激情",
    title_en: "Simple Passion",
    author: "annie-ernaux",
    author_zh: "安妮·埃尔诺",
    author_en: "Annie Ernaux",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1991,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "诺奖自传体小说，欲望与个人记忆",
    theme_en: "A Nobel laureate's autofiction of desire and personal memory.",
    tags: ["fiction","memoir","nobel-laureate","gender"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "the-persian-boy",
    category: "literature",
    title_zh: "波斯少年",
    title_en: "The Persian Boy",
    author: "mary-renault",
    author_zh: "玛丽·瑞瑙特",
    author_en: "Mary Renault",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 1972,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "亚历山大大帝远征，被征服者波斯太监视角",
    theme_en: "Alexander the Great's campaigns seen through the eyes of a Persian eunuch.",
    tags: ["fiction","novel","history","classics"],
    topics: ["literature","history"]
  },
  {
    slug: "a-whole-life",
    category: "literature",
    title_zh: "大雪将至（完整的一生）",
    title_en: "A Whole Life",
    author: "robert-seethaler",
    author_zh: "罗伯特·泽塔勒",
    author_en: "Robert Seethaler",
    nationality_zh: "奥地利",
    nationality_en: "Austria",
    year: 2014,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "普通人平淡而完整的一生",
    theme_en: "One ordinary man's quiet, complete life.",
    tags: ["fiction","novel","modernism"],
    topics: ["literature","modern-society"]
  },
  {
    slug: "bloodchild",
    category: "literature",
    title_zh: "血孩子",
    title_en: "Bloodchild",
    author: "octavia-butler",
    author_zh: "奥克塔维娅·巴特勒",
    author_en: "Octavia E. Butler",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1984,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "科幻双奖作品，屈从与寄生压迫",
    theme_en: "An award-winning sci-fi tale of submission and parasitic power.",
    tags: ["fiction","short-stories","dystopia","gender"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "the-lost-daughter",
    category: "literature",
    title_zh: "暗处的女儿",
    title_en: "The Lost Daughter",
    author: "elena-ferrante",
    author_zh: "埃莱娜·费兰特",
    author_en: "Elena Ferrante",
    nationality_zh: "意大利",
    nationality_en: "Italy",
    year: 2006,
    original_language: "it",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "母职解构与女性自我主体的剥离",
    theme_en: "Deconstructing motherhood, and a woman's loss of her own self.",
    tags: ["fiction","novel","gender","feminism"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "by-night-in-chile",
    category: "literature",
    title_zh: "智利之夜",
    title_en: "By Night in Chile",
    author: "roberto-bolano",
    author_zh: "罗贝托·波拉尼奥",
    author_en: "Roberto Bolaño",
    nationality_zh: "智利",
    nationality_en: "Chile",
    year: 2000,
    original_language: "es",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "知识分子的懦弱、逃避与政权共谋",
    theme_en: "An intellectual's cowardice, evasion, and complicity with a regime.",
    tags: ["fiction","novel","politics","modernism"],
    topics: ["literature","power-and-politics"]
  },
  {
    slug: "tokyo-refugees",
    category: "literature",
    title_zh: "一个贫穷的年轻人",
    title_en: "Tokyo Refugees",
    author: "tetsuzo-fukuzawa",
    author_zh: "福泽彻三",
    author_en: "Tetsuzo Fukuzawa",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 2011,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "青年贫困与心理扭曲变形",
    theme_en: "Youth poverty and the psychological damage it leaves behind.",
    tags: ["fiction","novel","japan","inequality"],
    topics: ["literature","class-and-inequality"]
  },
  {
    slug: "lao-ji-chao",
    category: "literature",
    title_zh: "老妓抄",
    title_en: null,
    author: "kanoko-okamoto",
    author_zh: "冈本加乃子",
    author_en: "Kanoko Okamoto",
    nationality_zh: "日本",
    nationality_en: "Japan",
    year: 1938,
    original_language: "ja",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "大正时代日式美学与女性视角",
    theme_en: "Taisho-era Japanese aesthetics and a woman's point of view.",
    tags: ["fiction","short-stories","japan","classics"],
    topics: ["literature","gender-and-family"]
  },
  {
    slug: "the-hunger-angel",
    category: "literature",
    title_zh: "呼吸秋千",
    title_en: "The Hunger Angel",
    author: "herta-muller",
    author_zh: "赫塔·米勒",
    author_en: "Herta Müller",
    nationality_zh: "德国/罗马尼亚",
    nationality_en: "Germany / Romania",
    year: 2009,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "诺奖作品，二战劳改营生存史",
    theme_en: "A Nobel laureate's account of survival in a wartime labour camp.",
    tags: ["fiction","novel","nobel-laureate","history"],
    topics: ["literature","authoritarianism"]
  },
  {
    slug: "digenis-akritas",
    category: "literature",
    title_zh: "狄吉尼斯·阿克里特",
    title_en: "Digenis Akritas",
    author: "anonymous",
    author_zh: "匿名",
    author_en: null,
    nationality_zh: "拜占庭帝国",
    nationality_en: "Byzantine Empire",
    year: null,
    original_language: "el",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "拜占庭边境史诗，基督教与伊斯兰冲突",
    theme_en: "A Byzantine frontier epic of the clash between Christianity and Islam.",
    tags: ["epic","poetry","classics","cultural-history"],
    topics: ["literature","history"]
  },
  {
    slug: "slaughterhouse-five",
    category: "literature",
    title_zh: "五号屠场",
    title_en: "Slaughterhouse-Five",
    author: "kurt-vonnegut",
    author_zh: "库尔特·冯内古特",
    author_en: "Kurt Vonnegut",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1969,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "德雷斯顿大轰炸与黑色幽默反战",
    theme_en: "The Dresden bombing and a blackly comic stand against war.",
    tags: ["fiction","novel","dystopia","modernism","world-wars"],
    topics: ["literature","existentialism"]
  },
  {
    slug: "a-canticle-for-leibowitz",
    category: "literature",
    title_zh: "莱博维兹的赞歌",
    title_en: "A Canticle for Leibowitz",
    author: "walter-m-miller-jr",
    author_zh: "小沃尔特·M·米勒",
    author_en: "Walter M. Miller Jr.",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1959,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "废土科幻，文明循环与历史遗忘",
    theme_en: "Post-apocalyptic sci-fi on the cycle of civilization and forgotten history.",
    tags: ["fiction","novel","dystopia","religion"],
    topics: ["literature","religion-and-meaning"]
  },
  {
    slug: "oresteia",
    category: "literature",
    title_zh: "俄瑞斯忒亚三部曲",
    title_en: "Oresteia",
    author: "aeschylus",
    author_zh: "埃斯库罗斯",
    author_en: "Aeschylus",
    nationality_zh: "古希腊",
    nationality_en: "Ancient Greece",
    year: -458,
    original_language: "el",
    tier: "list",
    source: "anzhengming",
    also_in: ["xiaomingshuo"],
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "经典神话悲剧，城邦法治与伦理冲突",
    theme_en: "A classic mythic tragedy of civic law and ethical conflict.",
    tags: ["drama","poetry","classics"],
    topics: ["literature","power-and-politics"]
  },
  {
    slug: "divan-of-hafez",
    category: "literature",
    title_zh: "设拉子夜莺",
    title_en: "Divan of Hafez",
    author: "hafez",
    author_zh: "哈菲兹",
    author_en: "Hafez",
    nationality_zh: "波斯",
    nationality_en: "Persia",
    year: null,
    original_language: "fa",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "波斯抒情诗歌与心灵抒发",
    theme_en: "Persian lyric poetry and the expression of the inner life.",
    tags: ["poetry","classics","religion","cultural-history"],
    topics: ["literature","religion-and-meaning"]
  },
  {
    slug: "the-summer-outside",
    category: "literature",
    title_zh: "外面是夏天",
    title_en: null,
    author: "ae-ran-kim",
    author_zh: "金爱烂",
    author_en: "Kim Ae-ran",
    nationality_zh: "韩国",
    nationality_en: "South Korea",
    year: 2017,
    original_language: "ko",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "现实主义小说，韩国当代普通人困境",
    theme_en: "Realist fiction about ordinary lives in contemporary Korea.",
    tags: ["fiction","short-stories","korea","modern-world"],
    topics: ["literature","modern-society"]
  },
  {
    slug: "lizi-xiaojie-yu-ziji-xiangchu",
    category: "literature",
    title_zh: "梨子小姐与自己相处",
    title_en: null,
    author: "bai-lu",
    author_zh: "白辂",
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: 2023,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "拒绝精神内耗，自我自洽",
    theme_en: "Refusing mental burnout, and learning to live at peace with oneself.",
    tags: ["fiction","novel","psychology","modern-world"],
    topics: ["literature","modern-society"]
  },
  {
    slug: "assemblywomen",
    category: "literature",
    title_zh: "公民大会妇女",
    title_en: "Assemblywomen",
    author: "aristophanes",
    author_zh: "阿里斯托芬",
    author_en: "Aristophanes",
    nationality_zh: "古希腊",
    nationality_en: "Ancient Greece",
    year: -392,
    original_language: "el",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "文学、小说与戏剧",
    list_category_en: "Literature, Fiction & Drama",
    theme_zh: "喜剧经典，古希腊消灭私有制寓言",
    theme_en: "A classical comedy imagining Athens without private property.",
    tags: ["drama","fiction","politics","classics"],
    topics: ["literature","gender-and-family"]
  }
];
