/**
 * 书单导入 · 批次 1
 * 由「安争鸣 / 小鸣说」YouTube 频道推荐书目整理而来。
 * 轻量条目：无长文简介，仅含书目事实字段 + 来源主题。
 * year / title_en 为 null 表示未能核实，不猜测。
 */
export const batch = [
  {
    slug: "liberalism",
    category: "society",
    title_zh: "自由与繁荣的国度",
    title_en: "Liberalism",
    author: "ludwig-von-mises",
    author_zh: "路德维希·冯·米瑟斯",
    author_en: "Ludwig von Mises",
    nationality_zh: "奥地利/美国",
    nationality_en: "Austria / United States",
    year: 1927,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "自由主义经济学，计划经济不可行论",
    theme_en: "Classical economics, and the case that central planning cannot work.",
    tags: ["liberalism","economics","capitalism","classics"],
    topics: ["democracy-and-liberty","power-and-politics"]
  },
  {
    slug: "the-feast-of-the-goat",
    category: "literature",
    title_zh: "公羊的节日",
    title_en: "The Feast of the Goat",
    author: "mario-vargas-llosa",
    author_zh: "马里奥·巴尔加斯·略萨",
    author_en: "Mario Vargas Llosa",
    nationality_zh: "秘鲁",
    nationality_en: "Peru",
    year: 2000,
    original_language: "es",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "独裁者独裁统治的丑态与崩塌",
    theme_en: "The grotesque spectacle and collapse of a dictator's rule.",
    tags: ["fiction","novel","politics","authoritarianism","nobel-laureate"],
    topics: ["literature","authoritarianism"]
  },
  {
    slug: "bad-beliefs",
    category: "society",
    title_zh: "坏信念",
    title_en: "Bad Beliefs: Why They Happen to Good People",
    author: "neil-levy",
    author_zh: "尼尔·利维",
    author_en: "Neil Levy",
    nationality_zh: "澳大利亚",
    nationality_en: "Australia",
    year: 2021,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "极端谬论、认知环境污染与坏信念",
    theme_en: "Extreme falsehoods, a polluted information environment, and bad beliefs.",
    tags: ["philosophy","psychology","cognitive-science","decision-making"],
    topics: ["cognitive-science","philosophy"]
  },
  {
    slug: "the-treason-of-the-intellectuals",
    category: "society",
    title_zh: "知识分子的背叛",
    title_en: "The Treason of the Intellectuals",
    author: "julien-benda",
    author_zh: "朱利安·班达",
    author_en: "Julien Benda",
    nationality_zh: "法国",
    nationality_en: "France",
    year: 1927,
    original_language: "fr",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "知识分子放弃真理、附庸政治极端的背叛",
    theme_en: "Intellectuals who abandon truth and surrender to political extremes.",
    tags: ["philosophy","politics","ethics","classics"],
    topics: ["power-and-politics","philosophy"]
  },
  {
    slug: "the-goodness-paradox",
    category: "society",
    title_zh: "人性悖论",
    title_en: "The Goodness Paradox: The Strange Relationship Between Virtue and Violence in Human Evolution",
    author: "richard-wrangham",
    author_zh: "理查德·兰厄姆",
    author_en: "Richard Wrangham",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2019,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "人类自我驯化与国家暴力机器",
    theme_en: "Human self-domestication and the machinery of state violence.",
    tags: ["human-nature","evolution","science","psychology"],
    topics: ["science-and-nature","civilization"]
  },
  {
    slug: "the-dictators-handbook",
    category: "society",
    title_zh: "独裁者手册",
    title_en: "The Dictator's Handbook: Why Bad Behavior Is Almost Always Good Politics",
    author: "bruce-bueno-de-mesquita",
    author_zh: "布鲁斯·布埃诺·德·梅斯奎塔",
    author_en: "Bruce Bueno de Mesquita",
    co_author_note: "原书单作者栏为「布鲁斯·布埃诺·德·梅斯奎塔等」，此处取第一作者；合著者为 Alastair Smith。",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2011,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "统治者政权维系与“致胜联盟”逻辑",
    theme_en: "How rulers stay in power by rewarding a winning coalition rather than the public.",
    tags: ["politics","institutions","power"],
    topics: ["power-and-politics","authoritarianism"]
  },
  {
    slug: "the-collapse-of-complex-societies",
    category: "society",
    title_zh: "复杂社会的崩溃",
    title_en: "The Collapse of Complex Societies",
    author: "joseph-tainter",
    author_zh: "约瑟夫·泰恩特",
    author_en: "Joseph Tainter",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1988,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "边际收益递减与复杂社会解体",
    theme_en: "Diminishing returns and the unraveling of complex societies.",
    tags: ["complexity","systems-thinking","history","civilization"],
    topics: ["complexity","civilization"]
  },
  {
    slug: "a-luminous-republic",
    category: "literature",
    title_zh: "光明共和国",
    title_en: "A Luminous Republic",
    author: "andres-barba",
    author_zh: "安德烈斯·巴尔瓦",
    author_en: "Andrés Barba",
    nationality_zh: "西班牙",
    nationality_en: "Spain",
    year: 2017,
    original_language: "es",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "白人文明秩序与“野蛮人”入侵隐喻",
    theme_en: "The order of white civilization and the fear of what lies outside it.",
    tags: ["fiction","novel","society"],
    topics: ["literature","modern-society"]
  },
  {
    slug: "the-palliative-society",
    category: "society",
    title_zh: "妥协社会：今日之痛",
    title_en: "The Palliative Society: Pain Today",
    author: "byung-chul-han",
    author_zh: "韩炳哲",
    author_en: "Byung-Chul Han",
    nationality_zh: "德国/韩国",
    nationality_en: "Germany / South Korea",
    year: 2020,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "屈服于制度强制与无力改革的妥协社会",
    theme_en: "A society that yields to institutional coercion and cannot reform itself.",
    tags: ["philosophy","society","modern-world"],
    topics: ["modern-society","philosophy"]
  },
  {
    slug: "21-lessons-for-the-21st-century",
    category: "society",
    title_zh: "今日简史",
    title_en: "21 Lessons for the 21st Century",
    author: "yuval-noah-harari",
    author_zh: "尤瓦尔·赫拉利",
    author_en: "Yuval Noah Harari",
    nationality_zh: "以色列",
    nationality_en: "Israel",
    year: 2018,
    original_language: "he",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "自由主义叙事破产与21世纪挑战",
    theme_en: "The collapse of the liberal story and the challenges of the 21st century.",
    tags: ["technology","society","future-of-technology","politics"],
    topics: ["technology","modern-society"]
  },
  {
    slug: "nexus",
    category: "society",
    title_zh: "智人之上",
    title_en: "Nexus: A Brief History of Information Networks from the Stone Age to AI",
    author: "yuval-noah-harari",
    author_zh: "尤瓦尔·赫拉利",
    author_en: "Yuval Noah Harari",
    nationality_zh: "以色列",
    nationality_en: "Israel",
    year: 2024,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "信息网络演化与数字极权监控",
    theme_en: "How information networks evolved, and how they enable digital surveillance.",
    tags: ["ai","technology","history","society"],
    topics: ["ai","technology"]
  },
  {
    slug: "homo-deus",
    category: "society",
    title_zh: "未来简史",
    title_en: "Homo Deus: A Brief History of Tomorrow",
    author: "yuval-noah-harari",
    author_zh: "尤瓦尔·赫拉利",
    author_en: "Yuval Noah Harari",
    nationality_zh: "以色列",
    nationality_en: "Israel",
    year: 2015,
    original_language: "he",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "科技人文主义、长生不老与阶级撕裂",
    theme_en: "Techno-humanism, immortality projects, and a society split by class.",
    tags: ["future-of-technology","technology","ai","human-nature"],
    topics: ["ai","modern-society"]
  },
  {
    slug: "civilized-to-death",
    category: "society",
    title_zh: "文明至死",
    title_en: "Civilized to Death: The Price of Progress",
    author: "christopher-ryan",
    author_zh: "克里斯托弗·瑞安",
    author_en: "Christopher Ryan",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2019,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "农业革命与现代文明困境反思",
    theme_en: "Reconsidering the agricultural revolution and the discontents of modern life.",
    tags: ["civilization","human-nature","progress","society"],
    topics: ["civilization","modern-society"]
  },
  {
    slug: "how-groups-encourage-misbehavior",
    category: "society",
    title_zh: "害马之群",
    title_en: "How Groups Encourage Misbehavior",
    author: "kevin-r-murphy",
    author_zh: "凯文·墨菲",
    author_en: "Kevin R. Murphy",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 2021,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "群体失控如何助长个体作恶",
    theme_en: "How groups lose control and push their members toward wrongdoing.",
    tags: ["psychology","organization","society","ethics"],
    topics: ["management","modern-society"]
  },
  {
    slug: "envy",
    category: "society",
    title_zh: "嫉妒与社会",
    title_en: "Envy: A Theory of Social Behaviour",
    author: "helmut-schoeck",
    author_zh: "赫尔穆特·舍克",
    author_en: "Helmut Schoeck",
    nationality_zh: "德国",
    nationality_en: "Germany",
    year: 1966,
    original_language: "de",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "嫉妒心理对社会行为与政治立场的扭曲",
    theme_en: "How envy distorts social behaviour and political allegiance.",
    tags: ["society","psychology","inequality","philosophy"],
    topics: ["class-and-inequality","modern-society"]
  },
  {
    slug: "the-right-nation",
    category: "society",
    title_zh: "右派国家",
    title_en: "The Right Nation: Conservative Power in America",
    author: "john-micklethwait",
    author_zh: "约翰·米克尔思韦特",
    author_en: "John Micklethwait",
    co_author_note: "原书单作者栏为「约翰·米克尔思韦特等」，此处取第一作者；合著者为 Adrian Wooldridge。",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2004,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "美国政治底色与保守主义力量",
    theme_en: "The conservative current running beneath American politics.",
    tags: ["politics","united-states","history","democracy"],
    topics: ["united-states","power-and-politics"]
  },
  {
    slug: "the-conformist",
    category: "literature",
    title_zh: "同流者",
    title_en: "The Conformist",
    author: "alberto-moravia",
    author_zh: "阿尔伯特·莫拉维亚",
    author_en: "Alberto Moravia",
    nationality_zh: "意大利",
    nationality_en: "Italy",
    year: 1951,
    original_language: "it",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "平庸普通人沦为暴政同谋",
    theme_en: "An ordinary man drifts into complicity with tyranny.",
    tags: ["fiction","novel","authoritarianism","politics"],
    topics: ["literature","authoritarianism"]
  },
  {
    slug: "how-change-happens",
    category: "society",
    title_zh: "变革如何发生",
    title_en: "How Change Happens",
    author: "duncan-green",
    author_zh: "邓肯·格林",
    author_en: "Duncan Green",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2016,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "社会变革演进机制与制度阻力",
    theme_en: "The mechanics of social change and the resistance of institutions.",
    tags: ["society","politics","institutions","globalization"],
    topics: ["power-and-politics","modern-society"]
  },
  {
    slug: "against-elections",
    category: "society",
    title_zh: "反对选举",
    title_en: "Against Elections: The Case for Democracy",
    author: "david-van-reybrouck",
    author_zh: "达维德·范雷布鲁克",
    author_en: "David Van Reybrouck",
    nationality_zh: "比利时",
    nationality_en: "Belgium",
    year: 2013,
    original_language: "nl",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "代表制选举缺陷与民主信任危机",
    theme_en: "The flaws of representative elections and the crisis of faith in democracy.",
    tags: ["democracy","politics","institutions","liberalism"],
    topics: ["democracy-and-liberty","power-and-politics"]
  },
  {
    slug: "propaganda-technique-in-the-world-war",
    category: "society",
    title_zh: "世界大战中的宣传技巧",
    title_en: "Propaganda Technique in the World War",
    author: "harold-lasswell",
    author_zh: "哈罗德·拉斯韦尔",
    author_en: "Harold D. Lasswell",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1927,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "政府大外宣策略与大众心理洗脑",
    theme_en: "Wartime state propaganda and the psychological manipulation of the masses.",
    tags: ["propaganda","world-wars","politics","history"],
    topics: ["power-and-politics","history"]
  },
  {
    slug: "capitalism-socialism-and-democracy",
    category: "society",
    title_zh: "资本主义、社会主义与民主",
    title_en: "Capitalism, Socialism and Democracy",
    author: "joseph-schumpeter",
    author_zh: "约瑟夫·熊彼特",
    author_en: "Joseph Schumpeter",
    nationality_zh: "美国/奥地利",
    nationality_en: "United States / Austria",
    year: 1942,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "创造性破坏与马克思主义宗教化",
    theme_en: "Creative destruction, and Marxism turned into a secular religion.",
    tags: ["capitalism","democracy","economics","politics"],
    topics: ["democracy-and-liberty","class-and-inequality"]
  },
  {
    slug: "shi-wo-de-cuo-ma",
    category: "society",
    title_zh: "是我的错吗？",
    title_en: null,
    author: "wu-zandao",
    author_zh: "吴赞镐",
    author_en: null,
    nationality_zh: "韩国",
    nationality_en: "South Korea",
    year: 2022,
    original_language: "ko",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "集体暴力与国家机器威压",
    theme_en: "Collective violence and the crushing weight of the state.",
    tags: ["society","korea","inequality","modern-world"],
    topics: ["modern-society","class-and-inequality"]
  },
  {
    slug: "bad-or-the-dumbing-of-america",
    category: "society",
    title_zh: "恶俗",
    title_en: "BAD: or, The Dumbing of America",
    author: "paul-fussell",
    author_zh: "保罗·福赛尔",
    author_en: "Paul Fussell",
    nationality_zh: "美国",
    nationality_en: "United States",
    year: 1991,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "大众文化虚假包装与现代化恶俗",
    theme_en: "Fakery and vulgarity in American mass culture.",
    tags: ["united-states","cultural-history","society","art"],
    topics: ["art-and-culture","modern-society"]
  },
  {
    slug: "bei-panchu-sixing-zhihou",
    category: "society",
    title_zh: "被判处死刑之后",
    title_en: null,
    author: "unknown-bei-panchu",
    author_zh: null,
    author_en: null,
    nationality_zh: "中国",
    nationality_en: "China",
    year: null,
    original_language: "zh",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "监禁、看守所生态与人性欲望",
    theme_en: "Life inside detention, the ecology of the prison, and human desire.",
    tags: ["china","society","memoir","inequality"],
    topics: ["modern-society","china-and-the-world"]
  },
  {
    slug: "helen-of-troy",
    category: "history",
    title_zh: "特洛伊的海伦",
    title_en: "Helen of Troy: Goddess, Princess, Whore",
    author: "bettany-hughes",
    author_zh: "贝尼塔·休斯",
    author_en: "Bettany Hughes",
    nationality_zh: "英国",
    nationality_en: "United Kingdom",
    year: 2005,
    original_language: "en",
    tier: "list",
    source: "anzhengming",
    list_category_zh: "政治学、社会学与制度批判",
    list_category_en: "Politics, Sociology & Institutional Critique",
    theme_zh: "外貌文化、女神符号与权力塑造",
    theme_en: "Beauty culture, the goddess as symbol, and the making of power.",
    tags: ["ancient-civilizations","history","cultural-history","gender"],
    topics: ["history","gender-and-family"]
  }
];
