/**
 * 双语检索别名表
 * 作用：让中文关键词能命中英文内容，反之亦然。
 * 结构：key 为触发词（小写），value 为需要一并匹配的等价词数组。
 * 检索时双向展开：命中 key 会加入 value；命中 value 中任一项也会加入 key。
 */
export const searchAliases = {
  // —— AI / 计算 ——
  人工智能: ['ai', 'artificial intelligence', 'machine intelligence'],
  ai: ['人工智能', '人工智慧', 'artificial intelligence'],
  通用人工智能: ['agi', 'artificial general intelligence', '超级智能', 'superintelligence'],
  agi: ['通用人工智能', 'artificial general intelligence', 'superintelligence'],
  机器学习: ['machine learning', 'ml', '深度学习', 'deep learning'],
  'machine learning': ['机器学习', '深度学习'],
  深度学习: ['deep learning', 'neural network', '神经网络'],
  'deep learning': ['深度学习', '神经网络'],
  神经网络: ['neural network', 'deep learning'],
  大语言模型: ['llm', 'large language model', 'gpt', '语言模型'],
  llm: ['大语言模型', 'large language model', '语言模型'],
  语言模型: ['language model', 'llm', '大语言模型'],
  强化学习: ['reinforcement learning', 'rl', '智能体', 'agent'],
  'reinforcement learning': ['强化学习', '智能体'],
  智能体: ['agent', 'agents', 'reinforcement learning', '强化学习'],
  算法: ['algorithm', 'algorithms', '计算', 'computing'],
  计算: ['computing', 'computation', 'computer science', '计算机科学'],
  计算机: ['computer', 'computing', '计算机科学'],
  计算机科学: ['computer science', 'computing', '计算'],
  图灵: ['turing', '计算', 'computing'],
  芯片: ['chip', 'chips', 'semiconductor', 'semiconductors', '半导体', '集成电路'],
  半导体: ['semiconductor', 'chip', 'chips', '芯片', '集成电路'],
  semiconductor: ['半导体', '芯片'],
  chip: ['芯片', '半导体', 'semiconductor'],
  集成电路: ['semiconductor', '芯片', 'integrated circuit'],
  材料: ['materials', 'material science', '材料科学'],
  物理: ['physics', '费曼', 'feynman'],
  科学: ['science', 'scientific', '科学革命'],
  技术: ['technology', 'tech', '技术革命'],
  technology: ['技术', '科技'],
  科技: ['technology', 'tech', '技术'],
  创新: ['innovation', 'innovator', 'disruption', '颠覆'],
  innovation: ['创新', '颠覆'],
  颠覆: ['disruption', 'disruptive', '创新者的窘境'],
  信息: ['information', '信息论', '媒介'],
  媒介: ['media', 'medium', 'understanding media', '传播'],

  // —— 金融 / 投资 ——
  金融: ['finance', 'financial', '金融史'],
  finance: ['金融'],
  投资: ['invest', 'investing', 'investment', 'investor'],
  investing: ['投资', '投资学'],
  investment: ['投资'],
  价值投资: ['value investing', 'graham', '格雷厄姆', '安全边际'],
  'value investing': ['价值投资', '安全边际'],
  安全边际: ['margin of safety', 'value investing', '价值投资'],
  成长投资: ['growth investing', '成长股'],
  股票: ['stock', 'stocks', 'equity', 'equities', '股市', '美股'],
  stock: ['股票', '美股', '股市'],
  美股: ['us stocks', 'us equities', 'wall street', '美国股市'],
  股市: ['stock market', 'market', '股票'],
  市场: ['market', 'markets', '市场先生'],
  指数基金: ['index fund', 'etf', '被动投资'],
  etf: ['指数基金', 'index fund', '被动投资'],
  资产配置: ['asset allocation', 'portfolio', '组合'],
  组合: ['portfolio', 'asset allocation', '资产配置'],
  风险: ['risk', 'risks', '风险控制'],
  risk: ['风险', '不确定性'],
  不确定性: ['uncertainty', 'uncertain', '黑天鹅', '概率'],
  uncertainty: ['不确定性', '黑天鹅'],
  概率: ['probability', 'probabilistic', '统计'],
  运气: ['luck', 'randomness', '随机', '随机性'],
  随机: ['random', 'randomness', '概率'],
  黑天鹅: ['black swan', 'the black swan', '极端事件'],
  'black swan': ['黑天鹅'],
  反脆弱: ['antifragile', 'antifragility', '脆弱'],
  antifragile: ['反脆弱'],
  泡沫: ['bubble', 'mania', 'crash', '崩盘', '狂热'],
  危机: ['crisis', 'crises', 'crash', '金融危机'],
  金融危机: ['financial crisis', 'crash', '危机'],
  货币: ['money', 'monetary', '货币史'],
  money: ['货币', '金钱'],
  央行: ['central bank', 'federal reserve', 'fed', '货币政策'],
  通货膨胀: ['inflation', '通胀', '物价'],
  inflation: ['通货膨胀', '通胀'],
  利率: ['interest rate', 'interest rates', '债券'],
  债券: ['bond', 'bonds', '固定收益', '利率'],
  银行: ['bank', 'banking', '银行体系'],
  金融史: ['financial history', 'history of finance', '货币史'],
  交易: ['trading', 'trader', '投机', 'speculation'],
  投机: ['speculation', 'speculator', '交易'],

  // —— 经济 ——
  经济: ['economy', 'economic', 'economics', '经济学'],
  经济学: ['economics', 'economy', '经济'],
  economics: ['经济学', '经济'],
  宏观经济: ['macroeconomics', 'macro', '宏观经济学'],
  宏观经济学: ['macroeconomics', 'macro'],
  微观经济学: ['microeconomics', 'micro'],
  增长: ['growth', 'economic growth', '经济增长'],
  制度: ['institution', 'institutions', '制度经济学'],
  国家: ['nation', 'nations', 'state', '国家能力'],
  贫困: ['poverty', 'poor', '贫穷'],
  繁荣: ['prosperity', 'wealth', '财富'],
  财富: ['wealth', 'capital', '资本'],
  资本: ['capital', 'capitalism', '资本主义'],
  资本主义: ['capitalism', 'capital', 'capitalist'],
  市场机制: ['market mechanism', '价格机制', '看不见的手'],
  税收: ['tax', 'taxation', '财政'],
  行为经济学: ['behavioral economics', 'behavioral', '行为金融'],
  行为金融: ['behavioral finance', '行为经济学'],

  // —— 历史 ——
  历史: ['history', 'historical', 'historian'],
  history: ['历史'],
  世界历史: ['world history', 'global history', '世界史'],
  文明: ['civilization', 'civilizations', '文明史'],
  civilization: ['文明'],
  帝国: ['empire', 'empires', 'imperial'],
  战争: ['war', 'wars', '世界大战'],
  世界大战: ['world war', 'world wars', '一战', '二战'],
  一战: ['world war i', 'first world war', 'great war'],
  二战: ['world war ii', 'second world war', '第三帝国'],
  冷战: ['cold war', '冷战史'],
  革命: ['revolution', 'revolutions', '工业革命'],
  工业革命: ['industrial revolution', 'revolution', '工业化'],
  罗马: ['rome', 'roman', 'roman empire', '罗马帝国'],
  希腊: ['greece', 'greek', '伯罗奔尼撒'],
  中国: ['china', 'chinese', '明代', '万历'],
  china: ['中国'],
  美国: ['united states', 'america', 'american', 'us'],
  america: ['美国', 'united states'],
  欧洲: ['europe', 'european', 'postwar'],
  全球化: ['globalization', 'global', '全球化史'],
  地缘政治: ['geopolitics', 'geopolitical', '国际关系'],
  秩序: ['order', 'world order', '国际秩序'],
  现代世界: ['modern world', 'modernity', '现代性'],

  // —— 商业 / 管理 ——
  商业: ['business', 'commerce', 'commercial'],
  business: ['商业'],
  创业: ['startup', 'startups', 'entrepreneurship', 'entrepreneur'],
  startup: ['创业', '初创公司'],
  战略: ['strategy', 'strategic', '竞争战略'],
  strategy: ['战略', '竞争'],
  竞争: ['competition', 'competitive', 'competitor', '竞争优势'],
  管理: ['management', 'manager', 'managerial'],
  management: ['管理'],
  组织: ['organization', 'organizational', '组织结构'],
  领导力: ['leadership', 'leader', '领导'],
  产品: ['product', 'product management', '产品设计'],
  设计: ['design', 'designer', '设计心理学'],
  商业模式: ['business model', 'business models', '盈利模式'],
  公司: ['company', 'corporate', '企业'],
  企业: ['company', 'enterprise', 'firm'],

  // —— 哲学 / 心理 ——
  哲学: ['philosophy', 'philosophical', 'philosopher'],
  philosophy: ['哲学'],
  伦理: ['ethics', 'ethical', '道德'],
  道德: ['moral', 'morality', 'ethics', '伦理'],
  斯多葛: ['stoicism', 'stoic', '斯多葛主义'],
  stoicism: ['斯多葛', '斯多葛主义'],
  存在主义: ['existentialism', 'existential', '西西弗'],
  自由: ['liberty', 'freedom', 'liberal'],
  正义: ['justice', 'fairness', '公正'],
  幸福: ['happiness', 'well-being', '美好生活'],
  死亡: ['death', 'mortality', '必死'],
  心智: ['mind', 'mental', '心智社会'],
  意识: ['consciousness', 'conscious', '自我意识'],
  心理学: ['psychology', 'psychological', 'psychologist'],
  psychology: ['心理学'],
  认知: ['cognitive', 'cognition', '认知科学'],
  认知科学: ['cognitive science', 'cognition', '认知'],
  偏见: ['bias', 'biases', '认知偏差'],
  噪声: ['noise', 'noisy', '判断噪声'],
  决策: ['decision', 'decision-making', '判断'],
  decision: ['决策', '判断'],
  判断: ['judgment', 'judgement', '判断力'],
  直觉: ['intuition', 'intuitive', '直觉思维'],
  理性: ['rational', 'rationality', '理性思维'],
  预测: ['forecast', 'forecasting', 'prediction', '预测力'],
  说服: ['persuasion', 'persuasive', '影响力'],
  影响力: ['influence', 'persuasion', '说服'],
  系统思考: ['systems thinking', 'system thinking', '系统思维'],
  系统: ['system', 'systems', '结构'],
  复杂性: ['complexity', 'complex', '涌现'],
  思维模型: ['mental model', 'mental models', '心智模型'],
  学习: ['learning', 'learn', '学习法'],
  习惯: ['habit', 'habits', '习惯养成'],
  动机: ['motivation', 'drive', '激励'],
  情绪: ['emotion', 'emotional', '情感'],

  // —— 社会 ——
  社会: ['society', 'social', '社会学'],
  society: ['社会'],
  文化: ['culture', 'cultural', '文化史'],
  权力: ['power', 'authority', '权力结构'],
  制度经济学: ['institutional economics', 'institutions', '制度'],
  宗教: ['religion', 'religious', '新教'],
  媒体: ['media', 'mass media', '媒介'],
  娱乐: ['entertainment', 'amusement', '娱乐至死'],
  人性: ['human nature', 'human', '人类'],
  进步: ['progress', 'progressive', '进步主义']
};

export default searchAliases;
